<a href="https://colab.research.google.com/github/GIRISH2409/Day1_ML/blob/main/Day1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day1

In [1]:
# Numpy

import numpy as np

a = [1,2,3,4]

arr1 = np.array(a)

b = [[1,2,3,4],[5,6,7,8]]

arr2 = np.array(b)

print(arr1)
print(arr2)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
print(type(a),type(arr1),type(b),type(arr2))


<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [3]:
import sys

s = range(1000)

print("size of each elment in the list in byters",sys.getsizeof(s
                                                                ))


size of each elment in the list in byters 48


In [5]:
#we are checking comparison between numpy size and normal size of sys package

import numpy as np

s = np.arange(1000)

print("size of each elements in the list by item size",s.itemsize)

print("complete list size in bytes", s.size*s.itemsize)





size of each elements in the list by item size 8
complete list size in bytes 8000


In [7]:
#import time library and execution time taking by the system

import time
a = range(1000)
b = range(1000)

start = time.time()

ab = [(a*b) for a,b in zip(a,b)]

end = time.time()
print("total time",end-start)


total time 0.0003139972686767578


In [11]:
import numpy as np
import time

arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

ab =  arr1*arr2

end = time.time()
print(ab)
print("total time",end - start)


[     0      1      4      9     16     25     36     49     64     81
    100    121    144    169    196    225    256    289    324    361
    400    441    484    529    576    625    676    729    784    841
    900    961   1024   1089   1156   1225   1296   1369   1444   1521
   1600   1681   1764   1849   1936   2025   2116   2209   2304   2401
   2500   2601   2704   2809   2916   3025   3136   3249   3364   3481
   3600   3721   3844   3969   4096   4225   4356   4489   4624   4761
   4900   5041   5184   5329   5476   5625   5776   5929   6084   6241
   6400   6561   6724   6889   7056   7225   7396   7569   7744   7921
   8100   8281   8464   8649   8836   9025   9216   9409   9604   9801
  10000  10201  10404  10609  10816  11025  11236  11449  11664  11881
  12100  12321  12544  12769  12996  13225  13456  13689  13924  14161
  14400  14641  14884  15129  15376  15625  15876  16129  16384  16641
  16900  17161  17424  17689  17956  18225  18496  18769  19044  19321
  1960

In [15]:
lst1 = [1,2,3,4]

arr = np.array(lst1)

print(arr)

lst1.append(6)
arr = np.array(lst1)
print(arr)
print(lst1)


[1 2 3 4]
[1 2 3 4 6]
[1, 2, 3, 4, 6]


In [18]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]], ndmin = 2)


print(arr1)







[[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np

arr1 = np.array([1,2,3])

print(arr1)


[1 2 3]


In [4]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.zeros((2,2))
print(arr2)


[[0. 0.]
 [0. 0.]]


In [8]:
 lst1 = [1,2,3,4,True,False,2+3j,'code']
 print(lst1)

[1, 2, 3, 4, True, False, (2+3j), 'code']


In [9]:
type(lst1)


list

In [ ]:
# different types of fata structures

# list - []

#tuple - ()

#Dictionar - {key:value}

#set = {numerical values and unique variables}



In [10]:
# creating a n dimensional array

a = [[1,2,3],[4,5,6]]

print(a)

[[1, 2, 3], [4, 5, 6]]


In [12]:
import numpy as np

np.array(a,ndmin=3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr[2,2]

9

In [18]:
# Numpy is for mathematical operations like creating and manipulating arrays and numbers

# Pandas - Is the data handling mechanism tool which can handle the datasets to process into models

np.random.rand(3,2)

array([[0.08124145, 0.55039865],
       [0.5235373 , 0.48591559],
       [0.03177969, 0.71476349]])

In [20]:
arr1= np.random.rand(3,2)

arr2 = np.random.rand(3,2)

s1 = np.add(arr1,arr2)
print(arr1)
print(arr2)
print(s1)

[[0.1343806  0.6791957 ]
 [0.60992116 0.25562372]
 [0.8941435  0.58243919]]
[[0.62586837 0.22453269]
 [0.4257396  0.32476193]
 [0.97531894 0.69754073]]
[[0.76024897 0.90372838]
 [1.03566076 0.58038566]
 [1.86946244 1.27997991]]


In [21]:
0.1343806+0.62586837


0.7602489699999999

In [28]:
#indexing and slicing

#step value means skipp a[0:10:2]

#reshape an array
import numpy as np

arr2 =np.array([[1,2,3,4],[5,6,7,8]])

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr2.shape


(2, 4)

In [33]:
arr2.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [34]:
# we are using html parser to acces data from a webpage

import pandas as pd

web = pd.read_html("https://en.wikipedia.org/wiki/Machine_learning")[3]

web.head()



0                                                  1
0 NaN  Wikimedia Commons has media related to Machine...

In [36]:
excel = pd.read_excel("/content/ex1.xlsx")

In [37]:
excel

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [38]:
excel.head()

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [39]:
excel.tail()

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo